name: minecraft
services:
  server:
    image: minecraft-server
    build:
      context: ./
      dockerfile: dockerfile.server
    container_name: server
    restart: always
    ports:
      - "25565:25565"
    volumes:
      - mods:/server/mods
      - world:/server/world

volumes:
  mods:
  world:
