FROM debian:latest

WORKDIR /server

RUN apt-get update \
    && apt-get install -y --no-install-recommends wget ca-certificates default-jre

COPY mods\. mods\.
COPY installer\. .
COPY custom_files\ .

RUN java -jar *.jar --installServer \
    && echo "eula=true" > eula.txt

CMD ["./custom.sh"]
